[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_bunked = "8FHD6Wi2VkqFJ1GoduSiLvKVqMcR7kunJ7Hd4oBSHvpV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sam/turbin3/turbindev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"
