[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_marketplace = "7ZjJpeM7TPowKV1P7AeFuMr6RM82CZyazhLKaiPH5jgc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
